### ISSUE TITLE
JRE does download over and over

### ISSUE THREAD

**Issue by geNAZt** [GoMint/minty#2]
JRE downloads should be detected first, currently they aren't detected at all which leads to a not found error which forces the installer to download the JRE over and over again

**Comment by chaplchapl** [comment]
Could you please elaborate?

> JRE downloads should be detected first

What kind of 'downloads' should be detected first? A JRE that is installed on the system or a JRE that was downloaded by Minty?

> [...] they aren't detected at all which leads to a not found error which forces the installer to download the JRE over and over again

That is correct. Minty currently does not check for the JRE downloaded by Minty and if no JRE was not found in the path or at a declared Java home, it will download the JRE again.

**Comment by geNAZt** [comment]
I assume that the JRE installed by minty should be detected first, then the system installed one (first JAVA_HOME then PATH)

**Comment by chaplchapl** [comment]
That is the case.

https://github.com/GoMint/minty/blob/ad3f80bf854829fd339b419962e453570c23b83b/internal/toolchain/jre/installation.go#L33-L60

**Comment by geNAZt** [comment]
This checks for JAVA_HOME not for ./jre/bin

**Comment by chaplchapl** [comment]
That's what I asked you to clarify. Quote: 
> What kind of 'downloads' should be detected first? A JRE that is installed on the system or a JRE that was downloaded by Minty? Minty checks the path or at a declared Java home for installed JREs.

I would estimate this bug to be fixed this weekend. No promises though. I would like to have a flexible way of how to manage JRE distributions and that involves creating a `.minty` directory somewhere on your system where various configurations and JRE distributions are being held.
