### ISSUE TITLE
Add <repo>:<commit> artifact selector

### ISSUE THREAD

**Issue by geNAZt** [GoMint/minty#3]
If i have a artifact built at commit 12345678 i want to be able to get the download link when i type "gomint:12345678".

**Comment by chaplchapl** [comment]
This sounds like cool functionality to have, but I'm afraid GitHub's API does not provide such functionality. You can get yourself a list of artifacts and search through them, but even then this wouldn't work, because an artifact doesn't expose a commit ID.

What I can implement is this:
```go
workflowRun, _, err := github.Actions.GetWorkflowRunByID(context.Background(), "gomint", repository, *latestArtifact.ID)
```
[...] where `workflowRun` exposes the following information:
```go
type WorkflowRun struct {
	ID             *int64         `json:"id,omitempty"`
	NodeID         *string        `json:"node_id,omitempty"`
	HeadBranch     *string        `json:"head_branch,omitempty"`
	HeadSHA        *string        `json:"head_sha,omitempty"`
	RunNumber      *int           `json:"run_number,omitempty"`
	Event          *string        `json:"event,omitempty"`
	Status         *string        `json:"status,omitempty"`
	Conclusion     *string        `json:"conclusion,omitempty"`
	URL            *string        `json:"url,omitempty"`
	HTMLURL        *string        `json:"html_url,omitempty"`
	PullRequests   []*PullRequest `json:"pull_requests,omitempty"`
	CreatedAt      *Timestamp     `json:"created_at,omitempty"`
	UpdatedAt      *Timestamp     `json:"updated_at,omitempty"`
	JobsURL        *string        `json:"jobs_url,omitempty"`
	LogsURL        *string        `json:"logs_url,omitempty"`
	CheckSuiteURL  *string        `json:"check_suite_url,omitempty"`
	ArtifactsURL   *string        `json:"artifacts_url,omitempty"`
	CancelURL      *string        `json:"cancel_url,omitempty"`
	RerunURL       *string        `json:"rerun_url,omitempty"`
	HeadCommit     *HeadCommit    `json:"head_commit,omitempty"`
	WorkflowURL    *string        `json:"workflow_url,omitempty"`
	Repository     *Repository    `json:"repository,omitempty"`
	HeadRepository *Repository    `json:"head_repository,omitempty"`
}
```
Please let me know if you'd like to propose something else considering this new 'evidence'.

**Comment by chaplchapl** [comment]
I just checked every single option and I'm afraid there's no way to implement the suggested functionality. I'm sorry. If this condition changes in the unforeseeable future, I will reopen this issue.

**Comment by chaplchapl** [comment]
![image](https://user-images.githubusercontent.com/64563583/85089085-fab2c800-b1e1-11ea-8b51-47aa2988c908.png)

Just to back my statement up. There's only a select group of fields one can access to perform a search. Searching via commit IDs is not available yet.
