### ISSUE TITLE
Add a roadmap/todo command

### ISSUE THREAD

**Issue by geNAZt** [GoMint/minty#7]
I want to have a simple way to slam stuff onto the issue tracker like a todo list. This should work for specific people in a group (like collaborators for example).

Usage would be:

!todo - Shows the list of todo's (done issues are removed from the list)
!todo #number - Add a existing issue to the todo list
!todo random test - Create a issue with the test as description and a title which increments on its own "Todo: Item #1" which i can edit later on adding to the todo list

The todo list itself should be stored inside the issues (with a todo label)

**Comment by chaplchapl** [comment]
This sounds reasonable and is easy to implement. There's one problem, though: How do you check whether user X on GoMint's Discord is allowed to perform such action? You'd technically have to do 1:1 name checking if you don't want to introduce a database or a third party service.

**Comment by geNAZt** [comment]
They get a group attached in discord

**Comment by chaplchapl** [comment]
> !todo - Shows the list of todo's (done issues are removed from the list)
-- Fetch all issues, filter via "todo" label, accept only the ones who are open

> !todo #number - Add an existing issue to the todo list
-- Lookup the referenced issue, continue if exists, apply todo label if not already applied

> !todo random test- Create an issue with the test as description and a title which increments on its own "Todo: Item #1" which i can edit later on adding to the todo list
-- So, as clarification, its meant to be a command that creates an issue with the description "random test". It's not a command altogether.
